In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Colab/NYC-EMS-Response/data/ny_events (1).csv')

In [4]:
# remove data outside NYC 5 B's
nyc = ['Bronx', # Bronx
 'Bronx/New York',
 'Bronx/New York/Queens',
 'Bronx/Queens',
 'New York / Bronx',
'Kings', # Brooklyn
 'Kings County',
 'Kings/New York',
 'Kings/Queens',
 'Kings/Richmond',
 'Brooklyn',
 'New York/Kings',
 'kings',
'Manhattan', # Manhattan
 'New York',
 'New Yrok',
 'New york',
'Queens County', # Queens
 'Queens/Kings/Nassau/Suffok',
 'Queens/New York',
 'New York/Queens',
'Richmond'] # Stat Rats

df = df[df['County'].isin(nyc)]

# drop useless cols
df.drop(columns=[
        'Event Type',
        'Organization Name',
        'Facility Name',
        'Direction',
        'Event Description',
        'Responding Organization Id',
        'State',
        'City'
], inplace=True)

# convert columns to datetime
df['Create Time']= pd.to_datetime(df['Create Time'])
df['Close Time']= pd.to_datetime(df['Close Time'])

# extract day, month, year, hour
df['year']=df['Create Time'].apply(lambda x: x.year)
df['month']=df['Create Time'].apply(lambda x: x.month)
df['day']=df['Create Time'].apply(lambda x: x.day)
df['hour']=df['Create Time'].apply(lambda x: x.hour)

In [5]:
df.shape

(170290, 9)

In [6]:
df.head()

      County         Create Time          Close Time  ...  month  day  hour
0      Bronx 2016-02-14 06:05:00 2016-02-14 07:03:00  ...      2   14     6
3   New York 2016-02-14 06:21:00 2016-02-14 13:28:00  ...      2   14     6
13     Bronx 2016-02-14 06:42:00 2016-02-14 07:01:00  ...      2   14     6
14     Bronx 2016-02-14 18:43:00 2016-02-14 18:47:00  ...      2   14    18
15  New York 2016-02-14 06:44:00 2016-02-14 11:23:00  ...      2   14     6

[5 rows x 9 columns]

In [ ]:
#df['Create Time'] = df['Create Time'].dt.tz_localize(tz='EST')

In [ ]:
#df['Create Time'] = df['Create Time'].dt.tz_convert(tz='UTC')

In [ ]:
#df['Create Time'] = df['Create Time'].astype(str)

In [ ]:
#new_time = [i[0:13] for i in df['Create Time']]

In [ ]:
#new_time = [datetime.strptime(i, '%Y-%m-%d %H') for i in new_time]

In [ ]:
#new_time = [i.timestamp() for i in new_time]

In [ ]:
#new_time = [int(i) for i in new_time]

In [ ]:
#df['UTC'] = new_time

In [7]:
new_county = []
for i in df['County']: 
  if i in ['Bronx','Bronx/New York','Bronx/New York/Queens','Bronx/Queens','New York / Bronx']:
    i = 'Bronx'
    new_county.append(i)
  elif i in ['Kings','Kings County','Kings/New York','Kings/Queens','Kings/Richmond','Brooklyn','New York/Kings','kings']:
    i = 'Brooklyn'
    new_county.append(i)
  elif i in ['Manhattan','New York','New Yrok','New york']:
    i = 'Manhattan'
    new_county.append(i)
  elif i in ['Queens County','Queens/Kings/Nassau/Suffok','Queens/New York','New York/Queens']:
    i = 'Queens'
    new_county.append(i)
  elif i in ['Richmond']:
    i = 'Richmond / Staten Island'
    new_county.append(i)
  else:
    print(i)

In [8]:
df['County'] = new_county

In [9]:
df.head()

       County         Create Time          Close Time  ...  month  day  hour
0       Bronx 2016-02-14 06:05:00 2016-02-14 07:03:00  ...      2   14     6
3   Manhattan 2016-02-14 06:21:00 2016-02-14 13:28:00  ...      2   14     6
13      Bronx 2016-02-14 06:42:00 2016-02-14 07:01:00  ...      2   14     6
14      Bronx 2016-02-14 18:43:00 2016-02-14 18:47:00  ...      2   14    18
15  Manhattan 2016-02-14 06:44:00 2016-02-14 11:23:00  ...      2   14     6

[5 rows x 9 columns]

In [10]:
df['Create Time'].min()

Timestamp('2010-01-02 02:51:00')

In [11]:
df['Create Time'].max()

Timestamp('2020-01-01 01:01:00')

In [ ]:
df[df['year'] == 2020]

           County         Create Time          Close Time  ...  month  day  hour
30867   Manhattan 2020-01-01 01:01:00 2020-01-01 01:16:00  ...      1    1     1
106370  Manhattan 2020-01-01 01:01:00 2020-01-01 01:16:00  ...      1    1     1
106598  Manhattan 2020-01-01 01:01:00 2020-01-01 01:16:00  ...      1    1     1

[3 rows x 9 columns]

In [25]:
new_df = df.groupby(["year", "month", "day", "hour"]).size().reset_index(name="Incidences")

In [26]:
new_df

       year  month  day  hour  Incidences
0      2010      1    2     2           1
1      2010      1    2     3           1
2      2010      1    3    12           1
3      2010      1    4     1           2
4      2010      1    4    10           2
...     ...    ...  ...   ...         ...
25470  2016      8   23    21           8
25471  2016      8   23    22          11
25472  2016      8   23    23           8
25473  2016      8   24    13           3
25474  2020      1    1     1           3

[25475 rows x 5 columns]

In [ ]:
new_df[new_df['year'] == 2020]

          County  year  month  day  hour  Incidences
55480  Manhattan  2020      1    1     1           3

In [14]:
data = pd.read_csv('/content/drive/MyDrive/Colab/NYC-EMS-Response/data/hourlycounts_weather.csv')

In [15]:
data

       year  month  day  hour  num_calls  ...  SNOW  SNWD  TMAX  TMIN  TAVG_CALC
0      2010      1    1     1        347  ...   0.0   0.0  40.0  33.0       36.5
1      2010      1    1     2        318  ...   0.0   0.0  40.0  33.0       36.5
2      2010      1    1     3        262  ...   0.0   0.0  40.0  33.0       36.5
3      2010      1    1     4        281  ...   0.0   0.0  40.0  33.0       36.5
4      2010      1    1     5        201  ...   0.0   0.0  40.0  33.0       36.5
...     ...    ...  ...   ...        ...  ...   ...   ...   ...   ...        ...
87626  2019     12   31    20        204  ...   0.0   0.0  45.0  36.0       40.5
87627  2019     12   31    21        239  ...   0.0   0.0  45.0  36.0       40.5
87628  2019     12   31    22        225  ...   0.0   0.0  45.0  36.0       40.5
87629  2019     12   31    23        214  ...   0.0   0.0  45.0  36.0       40.5
87630  2019     12   31    24        238  ...   0.0   0.0  45.0  36.0       40.5

[87631 rows x 20 columns]

In [17]:
data = data[(data['year'] <= 2016)]

In [19]:
data = data[(data['year'] >= 2010)]

In [20]:
data

       year  month  day  hour  num_calls  ...  SNOW  SNWD  TMAX  TMIN  TAVG_CALC
0      2010      1    1     1        347  ...   0.0   0.0  40.0  33.0       36.5
1      2010      1    1     2        318  ...   0.0   0.0  40.0  33.0       36.5
2      2010      1    1     3        262  ...   0.0   0.0  40.0  33.0       36.5
3      2010      1    1     4        281  ...   0.0   0.0  40.0  33.0       36.5
4      2010      1    1     5        201  ...   0.0   0.0  40.0  33.0       36.5
...     ...    ...  ...   ...        ...  ...   ...   ...   ...   ...        ...
61349  2016     12   31    20        195  ...   0.0   0.0  44.0  31.0       37.5
61350  2016     12   31    21        192  ...   0.0   0.0  44.0  31.0       37.5
61351  2016     12   31    22        205  ...   0.0   0.0  44.0  31.0       37.5
61352  2016     12   31    23        224  ...   0.0   0.0  44.0  31.0       37.5
61353  2016     12   31    24        198  ...   0.0   0.0  44.0  31.0       37.5

[61354 rows x 20 columns]

In [ ]:
#data.reset_index(inplace=True)

In [ ]:
# boro = []
# for i in range(8835):
#   if data['BOROUGH_BROOKLYN'][i] == 1:
#     boro.append("Brooklyn")
#   elif data['BOROUGH_MANHATTAN'][i] == 1:
#     boro.append("Manhattan")
#   elif data['BOROUGH_QUEENS'][i] == 1:
#     boro.append("Queens")
#   elif data['BOROUGH_RICHMOND / STATEN ISLAND'][i] == 1:
#     boro.append("Richmond / Staten Island")
#   else:
#     boro.append("Bronx")

In [ ]:
#data['Borough'] = boro

In [31]:
calls_weather_tfk = pd.merge(left=data, right=new_df,  how='inner', left_on=['year','month', 'day', 'hour'], right_on=['year','month','day', 'hour'])

In [32]:
calls_weather_tfk

       year  month  day  hour  ...  TMAX  TMIN  TAVG_CALC  Incidences
0      2010      1    2     2  ...  34.0  17.0       25.5           1
1      2010      1    2     3  ...  34.0  17.0       25.5           1
2      2010      1    3    12  ...  22.0  17.0       19.5           1
3      2010      1    4     1  ...  30.0  19.0       24.5           2
4      2010      1    4    10  ...  30.0  19.0       24.5           2
...     ...    ...  ...   ...  ...   ...   ...        ...         ...
25236  2016      8   23    20  ...  82.0  61.0       71.5          13
25237  2016      8   23    21  ...  82.0  61.0       71.5           8
25238  2016      8   23    22  ...  82.0  61.0       71.5          11
25239  2016      8   23    23  ...  82.0  61.0       71.5           8
25240  2016      8   24    13  ...  88.0  68.0       78.0           3

[25241 rows x 21 columns]

In [33]:
calls_weather_tfk['Incidences'].isnull().sum()

0

In [34]:
calls_weather_tfk.to_csv('/content/drive/MyDrive/Colab/NYC-EMS-Response/data/calls_weather_tfk.csv')